config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#index' # homepage
  get '/about', to: 'pages#about'  #pages about page
  get '/contact-us', to: 'pages#contact'  # contact us page
 
  resources :courses, only: [:new, :show, :index] # courses routes
  
  # here we nested get :email_confirm route into students becuase this action heppen when we create a new student. So email_confirm is now a memeber of student resources
  resources :students, except: [:destroy] do  # students routes
    member do
      get :email_confirm
    end
  end
    

  # sessions routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # student enroll on a course
  post 'course_enroll', to: 'student_courses#create'

  # email confirmation routes
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord

  before_create :confirmation_token

  before_save {self.email = email.downcase} # convert downcase email letters before saving into DB

  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 5, maximum: 30}

  validates :password, presence: true, length: {minimum: 5, maximum: 20}

  CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
  
  # validates email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, 
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: {with: VALID_EMAIL_REGEX}

  has_secure_password

  # Many-to-Many Association, student_courses
  has_many :student_courses
  has_many :courses, through: :student_courses



  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  private

  def confirmation_token
    if self.confirm_token.blank?
        self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  skip_before_action :require_user, only: [:new, :create] # to allow user to enroll
  before_action :set_student, only: [:show, :edit, :update]
  before_action :require_same_student, only: [:edit, :update] # to edit profile, student must logged in and the profile must belong to the logged in user. So logged in user can only edit their own profile

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def show
  end

  def edit
  end

  def update
    if @student.update(student_params)
      flash[:notice] = "Your profile has been successfully updated"
      redirect_to @student # or student_path(@student)
    else
      render :edit
    end
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      StudentMailer.student_email_confirmation(@student).deliver
        flash[:success] = "Please confirm your email address to continue"
        redirect_to login_path
        # this is for welcome message
      #StudentMailer.student_welcome(@student).deliver
      #flash[:notice] = "Welcome to Green University #{@student.name}."
      #redirect_to root_path
    else
      render :new
    end
  end

  def email_confirm
    student = Student.find_by_confirm_token(params[:id])
    if student
      student.email_activate
      flash[:success] = "Welcome to the Sample App! Your email has been confirmed.
      Please sign in to continue."
      redirect_to login
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to root_path
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def require_same_student
    if current_user != @student  # if profile viewing is not for current user
      flash[:notice] = "You can only edit your own profile"
      redirect_to student_path(current_user)
    end
  end

end

app/views/students/_form.html.erb
<h1><%= @student.new_record? ? "Enroll new student" : "Submit Changes" %></h1>
<%= render 'shared/error-messages', obj: @student %>

<%= form_for @student do |form| %>
  <div class="mb-3">
      <%= form.label :name, class:"form-label", for:"name"%>
      <%= form.text_field :name, class: "form-control", id:"name", placeholder: "enter your full name" %>
  </div>
  <div class="mb-3">
    <%= form.label :email, class:"form-label", for:"email" %>
    <%= form.email_field :email, class:"form-control", id:"email", placeholder: "enter your email address" %>
  </div>
  <div class="mb-3">
    <%= form.label :password, for:"password", class: "form-label" %>
    <%= form.password_field :password, id: "password", class: "form-control", placeholder: "choose a password" %>
  </div>
  <div class="mb-3">
    <%= form.label :password_confirmation, for:"password", class: "form-label" %>
    <%= form.password_field :password_confirmation, id: "password", class: "form-control", placeholder: "confirm your password" %>
  </div>

  <%= form.submit(@student.new_record? ? "Enroll" : "Submit Changes", class:"custom-btn") %>
<% end %>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<h1 class="text-center mb-5">Students Directory</h1>

<div class="wrapper">
  <div class="card-box">
  <% @students.each do |student| %>
    <div class="box">
      <div>
        <h3><%= student.name %></h3>
        <hr>
        <h6>Email: <%= student.email %></h6>
        <h6>Student Course(s):</h6><p> <% if student.courses.empty? %>
        None
        <% else %>
        <ul>
            <% student.courses.each do |course| %>
              <li><%= course.title %></li>
            <% end %>
        </ul>
        <% end %>
        </p>
      </div>
      <div>
        <hr>
        <%= link_to 'View Profile', student_path(student), class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="wrapper">
  <div class="card-box">
    <div class="box">
      <div>
        <h3><%= @student.name %></h3>
        <hr>
        <h6>Email: <%= @student.email %></h6>
        <h6>Student Course(s):</h6><p> <% if @student.courses.empty? %>
          None
          <% else %>
          <ul>
            <% @student.courses.each do |course| %>
              <li><%= course.title %></li>
            <% end %>
          </ul>
          <% end %>
         </p>
      </div>
    </div>
</div>
<% if current_user == @student %>
  <%= link_to 'Edit your profile', edit_student_path(@student), class: "custom-btn" %>
<% end %>