config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#index' # homepage
  get '/about', to: 'pages#about'  #pages about page
  get '/contact-us', to: 'pages#contact'  # contact us page
 
  resources :courses, only: [:new, :show, :index] # courses routes
  
  # here we nested get :email_confirm route into students becuase this action heppen when we create a new student. So email_confirm is now a memeber of student resources
  resources :students, except: [:destroy] do  # students routes
    member do
      get :email_confirm
    end
  end
    

  # sessions routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # student enroll on a course
  post 'course_enroll', to: 'student_courses#create'

  # email confirmation routes
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  skip_before_action :require_user  # User can see list of courses without login

  def index
    @courses = Course.all
  end

  def new
  end

  def show
    @course = Course.find(params[:id])
  end

end

app/views/courses/index.html.erb
<h1 class="text-center mb-5">Course Listing</h1>

<div class="wrapper">
  <div class="card-box">
  <% @courses.each do |course| %>
    <div class="box">
      <div>
        <h3><%= course.code %>: <%= course.title%></h3>
        <p><%= course.description %></p>
      </div>
      <div>
        <hr>
        <% if logged_in? && !(current_user.courses.include?(course)) %> <% 'COMMENT: check if user logged in and user not already enrolled on the course' %>
          <%= link_to 'Enroll in this course', course_enroll_path(course_id: course.id), method: :post, class:"btn btn-success" %>
        <% end %>
        <%= link_to 'Read More', course_path(course), class:"btn btn-info" %>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/new.html.erb
<h1 class="text-center">New course page</h1>

app/views/courses/show.html.erb
<h1>Course Details</h1>