config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#index' # homepage
  get '/about', to: 'pages#about'  #pages about page
  get '/contact-us', to: 'pages#contact'  # contact us page
 
  resources :courses, only: [:new, :show, :index] # courses routes
  
  # here we nested get :email_confirm route into students becuase this action heppen when we create a new student. So email_confirm is now a memeber of student resources
  resources :students, except: [:destroy] do  # students routes
    member do
      get :email_confirm
    end
  end
    

  # sessions routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # student enroll on a course
  post 'course_enroll', to: 'student_courses#create'

  # email confirmation routes
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class="footer_info container">
  <div>
    <h3>Green University</h3>
    <p>The future of development training</p>
  </div>
  <div class="footer_contact">
    <h3>Information</h3>
    <ul class="ul">
      <li>
        <%= link_to 'Home', root_path, class: "nav-a-custom" %>
      </li>
      <li>
        <%= link_to 'About', about_path, class: "nav-a-custom" %>
      </li>
      <li>
        <%= link_to 'Courses', courses_path, class: "nav-a-custom" %>
      </li>
      <li>
         <%= link_to 'Contact Us', contact_us_path, class: "nav-a-custom" %>
      </li>
      </ul>
      </div>
  </div>
</div>
</footer>
<div class="text-center custom-footer">
  <samll class="container">&copy; 2022 <%= link_to "Green University", "https://green-university.herokuapp.com/", class: "footer_link" %></samll>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-success alert-dismissible fade show"" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light nav-custom">
  <div class="container">
    <%= link_to 'Green University', root_path, class: "navbar-brand nav-a-logo-custom" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', about_path, class: "nav-link nav-a-custom" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Courses', courses_path, class: "nav-link nav-a-custom" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to 'Students', students_path, class: "nav-link nav-a-custom" %>
          </li>
        <% end %>
          <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle nav-a-custom" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <ul class="dropdown-menu nav-a-custom" aria-labelledby="navbarDropdown">

            <%= link_to 'View Profile', student_path(current_user), class:"dropdown-item" %>
            <li><a class="dropdown-item" href="#">View courses</a></li>
          <% end %>
          </ul>
        </li>
      </ul>
      <ul class="sign-up-login-custom">
        <% if (logged_in?) %>
          <li><%= link_to 'Logout', logout_path, method: :delete, class: " nav-link nav-a-custom added-style" %></li>
          <% else %>
            <li><%= link_to 'Login', login_path, class: " nav-link nav-a-custom added-style" %></li>
            <li><%= link_to 'Sign up', new_student_path, class: " nav-link nav-a-custom added-style" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GreenUniversity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="Site">
    <%= render 'layouts/navigation' %>
    <main class="Site-content">
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

    </main>
    <%= render 'layouts/footer' %> 
  </body>
</html>